name: 'Dependency Check'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Check'
        uses: actions/dependency-review-action@v4