name: Update App
on:
  push:
    branches:
      - prod

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: bun

      - name: Navigate to app directory
        run: cd ./app

      - name: Navigate to project
        run: cd packages/app

      - name: Install dependencies
        run: bun install

      - name: Publish update
        run: bunx eas update --auto --non-interactive
